### ISSUE TITLE
Is there a way to use all projects in a workspace?

### ISSUE THREAD

**Issue by smoovej** [edi-design/asana-hipchat#15]
I've tried setting $ALLOWED_PROJECTS to NULL, and that doesn't seem to do the trick.  

Thanks!

**Comment by edi-design** [comment]
Sorry for the late answer.

set it to NULL should work fine.
Have you kept the '' around the NULL?

Please try this:
define('ALLOWED_PROJECTS', NULL);

Or simply remove the define() line. This automatically act as null. This is the setup i am using.

If this doesn't work, please drop me a line and i will check again.
